title: Abdullatif Mahmoud
logo: /assets/img/MyLogo.png
description: Structural Engineer & Designer
show_downloads: true
theme: jekyll-theme-minimal

# Custom field for portfolio PDF
portfolio_pdf: /assets/files/Abdullatif Protofolio.pdf
