title: Abdullatif Mahmoud
logo: /assets/img/headshot_circle.png
description: Structural Engineer & Designer
show_downloads: true
theme: jekyll-theme-minimal

# Custom field for portfolio PDF
portfolio_pdf: /assets/files/ShawTalebi_Portfolio.pdf
